FROM python3:latest
RUN python36 -m pip install  xgboost xlrd pandas matplotlib scikit-learn -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com --no-cache-dir --upgrade pip \
    #如果需要开发环境，则将此行注释